/* Automatically generated by tree-sitter v0.25.2 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 79
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 41
#define ALIAS_COUNT 0
#define TOKEN_COUNT 24
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 11
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_comment = 1,
  anon_sym_entry = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  anon_sym_reference = 5,
  anon_sym_EQ = 6,
  anon_sym_for = 7,
  anon_sym_LPAREN = 8,
  anon_sym_RPAREN = 9,
  anon_sym_in = 10,
  anon_sym_add = 11,
  anon_sym_rm = 12,
  anon_sym_remove = 13,
  anon_sym_sub = 14,
  anon_sym_subtract = 15,
  anon_sym_credit = 16,
  anon_sym_debit = 17,
  anon_sym_DASH_GT = 18,
  sym_identifier = 19,
  sym_number = 20,
  aux_sym_string_token1 = 21,
  anon_sym_true = 22,
  anon_sym_false = 23,
  sym_source_file = 24,
  sym__statement = 25,
  sym_entry = 26,
  sym_reference = 27,
  sym_assignment = 28,
  sym_transaction = 29,
  sym_scoped_transaction = 30,
  sym__transaction_statement = 31,
  sym_special_transaction = 32,
  sym_entity_reference = 33,
  sym__value = 34,
  sym_string = 35,
  sym_boolean = 36,
  aux_sym_source_file_repeat1 = 37,
  aux_sym_transaction_repeat1 = 38,
  aux_sym_scoped_transaction_repeat1 = 39,
  aux_sym_entity_reference_repeat1 = 40,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [anon_sym_entry] = "entry",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_reference] = "reference",
  [anon_sym_EQ] = "=",
  [anon_sym_for] = "for",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_in] = "in",
  [anon_sym_add] = "add",
  [anon_sym_rm] = "rm",
  [anon_sym_remove] = "remove",
  [anon_sym_sub] = "sub",
  [anon_sym_subtract] = "subtract",
  [anon_sym_credit] = "credit",
  [anon_sym_debit] = "debit",
  [anon_sym_DASH_GT] = "->",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_entry] = "entry",
  [sym_reference] = "reference",
  [sym_assignment] = "assignment",
  [sym_transaction] = "transaction",
  [sym_scoped_transaction] = "scoped_transaction",
  [sym__transaction_statement] = "_transaction_statement",
  [sym_special_transaction] = "special_transaction",
  [sym_entity_reference] = "entity_reference",
  [sym__value] = "_value",
  [sym_string] = "string",
  [sym_boolean] = "boolean",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_transaction_repeat1] = "transaction_repeat1",
  [aux_sym_scoped_transaction_repeat1] = "scoped_transaction_repeat1",
  [aux_sym_entity_reference_repeat1] = "entity_reference_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [anon_sym_entry] = anon_sym_entry,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_reference] = anon_sym_reference,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_for] = anon_sym_for,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_add] = anon_sym_add,
  [anon_sym_rm] = anon_sym_rm,
  [anon_sym_remove] = anon_sym_remove,
  [anon_sym_sub] = anon_sym_sub,
  [anon_sym_subtract] = anon_sym_subtract,
  [anon_sym_credit] = anon_sym_credit,
  [anon_sym_debit] = anon_sym_debit,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_entry] = sym_entry,
  [sym_reference] = sym_reference,
  [sym_assignment] = sym_assignment,
  [sym_transaction] = sym_transaction,
  [sym_scoped_transaction] = sym_scoped_transaction,
  [sym__transaction_statement] = sym__transaction_statement,
  [sym_special_transaction] = sym_special_transaction,
  [sym_entity_reference] = sym_entity_reference,
  [sym__value] = sym__value,
  [sym_string] = sym_string,
  [sym_boolean] = sym_boolean,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_transaction_repeat1] = aux_sym_transaction_repeat1,
  [aux_sym_scoped_transaction_repeat1] = aux_sym_scoped_transaction_repeat1,
  [aux_sym_entity_reference_repeat1] = aux_sym_entity_reference_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_entry] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_reference] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_for] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_add] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_rm] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_remove] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_sub] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_subtract] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_credit] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_debit] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_transaction] = {
    .visible = true,
    .named = true,
  },
  [sym_scoped_transaction] = {
    .visible = true,
    .named = true,
  },
  [sym__transaction_statement] = {
    .visible = false,
    .named = true,
  },
  [sym_special_transaction] = {
    .visible = true,
    .named = true,
  },
  [sym_entity_reference] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_transaction_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_scoped_transaction_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_entity_reference_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 11,
  [15] = 13,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 17,
  [23] = 18,
  [24] = 20,
  [25] = 19,
  [26] = 21,
  [27] = 27,
  [28] = 28,
  [29] = 20,
  [30] = 30,
  [31] = 31,
  [32] = 16,
  [33] = 18,
  [34] = 19,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 37,
  [39] = 37,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 43,
  [48] = 46,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 56,
  [63] = 49,
  [64] = 64,
  [65] = 65,
  [66] = 61,
  [67] = 49,
  [68] = 53,
  [69] = 64,
  [70] = 70,
  [71] = 53,
  [72] = 58,
  [73] = 61,
  [74] = 51,
  [75] = 65,
  [76] = 50,
  [77] = 77,
  [78] = 57,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(49);
      ADVANCE_MAP(
        '(', 60,
        ')', 61,
        '-', 2,
        '/', 1,
        '=', 57,
        'a', 12,
        'c', 34,
        'd', 14,
        'e', 27,
        'f', 3,
        'i', 28,
        'r', 15,
        's', 42,
        't', 35,
        '{', 53,
        '}', 54,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(117);
      END_STATE();
    case 1:
      if (lookahead == '/') ADVANCE(50);
      END_STATE();
    case 2:
      if (lookahead == '>') ADVANCE(78);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(26);
      if (lookahead == 'o') ADVANCE(31);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(9);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(85);
      if (lookahead == 'c') ADVANCE(108);
      if (lookahead == 'd') ADVANCE(89);
      if (lookahead == 'f') ADVANCE(102);
      if (lookahead == 'r') ADVANCE(90);
      if (lookahead == 's') ADVANCE(113);
      if (lookahead == '}') ADVANCE(54);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(85);
      if (lookahead == 'c') ADVANCE(108);
      if (lookahead == 'd') ADVANCE(89);
      if (lookahead == 'r') ADVANCE(90);
      if (lookahead == 's') ADVANCE(113);
      if (lookahead == '}') ADVANCE(54);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 7:
      if (lookahead == 'b') ADVANCE(24);
      END_STATE();
    case 8:
      if (lookahead == 'b') ADVANCE(70);
      END_STATE();
    case 9:
      if (lookahead == 'c') ADVANCE(40);
      END_STATE();
    case 10:
      if (lookahead == 'c') ADVANCE(19);
      END_STATE();
    case 11:
      if (lookahead == 'd') ADVANCE(64);
      END_STATE();
    case 12:
      if (lookahead == 'd') ADVANCE(11);
      END_STATE();
    case 13:
      if (lookahead == 'd') ADVANCE(25);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(7);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(23);
      if (lookahead == 'm') ADVANCE(66);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(121);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(122);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(68);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(55);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(13);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(29);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(36);
      END_STATE();
    case 23:
      if (lookahead == 'f') ADVANCE(22);
      if (lookahead == 'm') ADVANCE(30);
      END_STATE();
    case 24:
      if (lookahead == 'i') ADVANCE(38);
      END_STATE();
    case 25:
      if (lookahead == 'i') ADVANCE(39);
      END_STATE();
    case 26:
      if (lookahead == 'l') ADVANCE(37);
      END_STATE();
    case 27:
      if (lookahead == 'n') ADVANCE(41);
      END_STATE();
    case 28:
      if (lookahead == 'n') ADVANCE(62);
      END_STATE();
    case 29:
      if (lookahead == 'n') ADVANCE(10);
      END_STATE();
    case 30:
      if (lookahead == 'o') ADVANCE(44);
      END_STATE();
    case 31:
      if (lookahead == 'r') ADVANCE(58);
      END_STATE();
    case 32:
      if (lookahead == 'r') ADVANCE(45);
      END_STATE();
    case 33:
      if (lookahead == 'r') ADVANCE(4);
      END_STATE();
    case 34:
      if (lookahead == 'r') ADVANCE(20);
      END_STATE();
    case 35:
      if (lookahead == 'r') ADVANCE(43);
      END_STATE();
    case 36:
      if (lookahead == 'r') ADVANCE(21);
      END_STATE();
    case 37:
      if (lookahead == 's') ADVANCE(17);
      END_STATE();
    case 38:
      if (lookahead == 't') ADVANCE(76);
      END_STATE();
    case 39:
      if (lookahead == 't') ADVANCE(74);
      END_STATE();
    case 40:
      if (lookahead == 't') ADVANCE(72);
      END_STATE();
    case 41:
      if (lookahead == 't') ADVANCE(32);
      END_STATE();
    case 42:
      if (lookahead == 'u') ADVANCE(8);
      END_STATE();
    case 43:
      if (lookahead == 'u') ADVANCE(16);
      END_STATE();
    case 44:
      if (lookahead == 'v') ADVANCE(18);
      END_STATE();
    case 45:
      if (lookahead == 'y') ADVANCE(51);
      END_STATE();
    case 46:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(46);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 47:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(118);
      END_STATE();
    case 48:
      if (eof) ADVANCE(49);
      if (lookahead == '/') ADVANCE(1);
      if (lookahead == 'e') ADVANCE(99);
      if (lookahead == 'f') ADVANCE(102);
      if (lookahead == 'i') ADVANCE(100);
      if (lookahead == 'r') ADVANCE(87);
      if (lookahead == '}') ADVANCE(54);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(48);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_entry);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_entry);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_reference);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_reference);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_for);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_for);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_in);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_add);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_add);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_rm);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_rm);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_remove);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_remove);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_sub);
      if (lookahead == 't') ADVANCE(33);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_sub);
      if (lookahead == 't') ADVANCE(106);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_subtract);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_subtract);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_credit);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_credit);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_debit);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_debit);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(83);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'b') ADVANCE(96);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'b') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(88);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(111);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(84);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(97);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(95);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(80);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(98);
      if (lookahead == 'm') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(69);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(101);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(107);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(93);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(109);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(110);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(103);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(112);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(82);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(104);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(114);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(115);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(79);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(92);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(94);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(77);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(75);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(105);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(81);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'v') ADVANCE(91);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'y') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(117);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(118);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(119);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(120);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(120);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 48},
  [2] = {.lex_state = 5},
  [3] = {.lex_state = 5},
  [4] = {.lex_state = 48},
  [5] = {.lex_state = 5},
  [6] = {.lex_state = 48},
  [7] = {.lex_state = 48},
  [8] = {.lex_state = 48},
  [9] = {.lex_state = 48},
  [10] = {.lex_state = 48},
  [11] = {.lex_state = 6},
  [12] = {.lex_state = 6},
  [13] = {.lex_state = 6},
  [14] = {.lex_state = 6},
  [15] = {.lex_state = 6},
  [16] = {.lex_state = 5},
  [17] = {.lex_state = 5},
  [18] = {.lex_state = 5},
  [19] = {.lex_state = 5},
  [20] = {.lex_state = 5},
  [21] = {.lex_state = 5},
  [22] = {.lex_state = 6},
  [23] = {.lex_state = 6},
  [24] = {.lex_state = 6},
  [25] = {.lex_state = 6},
  [26] = {.lex_state = 48},
  [27] = {.lex_state = 48},
  [28] = {.lex_state = 48},
  [29] = {.lex_state = 48},
  [30] = {.lex_state = 48},
  [31] = {.lex_state = 48},
  [32] = {.lex_state = 48},
  [33] = {.lex_state = 48},
  [34] = {.lex_state = 48},
  [35] = {.lex_state = 48},
  [36] = {.lex_state = 48},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 46},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 46},
  [46] = {.lex_state = 46},
  [47] = {.lex_state = 46},
  [48] = {.lex_state = 46},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 119},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 46},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 119},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 119},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [anon_sym_entry] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_reference] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_for] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_add] = ACTIONS(1),
    [anon_sym_rm] = ACTIONS(1),
    [anon_sym_remove] = ACTIONS(1),
    [anon_sym_sub] = ACTIONS(1),
    [anon_sym_subtract] = ACTIONS(1),
    [anon_sym_credit] = ACTIONS(1),
    [anon_sym_debit] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(77),
    [sym__statement] = STATE(10),
    [sym_entry] = STATE(10),
    [sym_reference] = STATE(10),
    [sym_assignment] = STATE(10),
    [sym_transaction] = STATE(10),
    [sym_scoped_transaction] = STATE(10),
    [aux_sym_source_file_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [anon_sym_entry] = ACTIONS(7),
    [anon_sym_reference] = ACTIONS(9),
    [anon_sym_for] = ACTIONS(11),
    [anon_sym_in] = ACTIONS(13),
    [sym_identifier] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(17), 1,
      anon_sym_RBRACE,
    ACTIONS(19), 1,
      anon_sym_for,
    ACTIONS(23), 1,
      sym_identifier,
    STATE(5), 5,
      sym_assignment,
      sym_transaction,
      sym__transaction_statement,
      sym_special_transaction,
      aux_sym_scoped_transaction_repeat1,
    ACTIONS(21), 7,
      anon_sym_add,
      anon_sym_rm,
      anon_sym_remove,
      anon_sym_sub,
      anon_sym_subtract,
      anon_sym_credit,
      anon_sym_debit,
  [26] = 5,
    ACTIONS(19), 1,
      anon_sym_for,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(25), 1,
      anon_sym_RBRACE,
    STATE(2), 5,
      sym_assignment,
      sym_transaction,
      sym__transaction_statement,
      sym_special_transaction,
      aux_sym_scoped_transaction_repeat1,
    ACTIONS(21), 7,
      anon_sym_add,
      anon_sym_rm,
      anon_sym_remove,
      anon_sym_sub,
      anon_sym_subtract,
      anon_sym_credit,
      anon_sym_debit,
  [52] = 8,
    ACTIONS(29), 1,
      sym_comment,
    ACTIONS(32), 1,
      anon_sym_entry,
    ACTIONS(35), 1,
      anon_sym_reference,
    ACTIONS(38), 1,
      anon_sym_for,
    ACTIONS(41), 1,
      anon_sym_in,
    ACTIONS(44), 1,
      sym_identifier,
    ACTIONS(27), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    STATE(4), 7,
      sym__statement,
      sym_entry,
      sym_reference,
      sym_assignment,
      sym_transaction,
      sym_scoped_transaction,
      aux_sym_source_file_repeat1,
  [84] = 5,
    ACTIONS(47), 1,
      anon_sym_RBRACE,
    ACTIONS(49), 1,
      anon_sym_for,
    ACTIONS(55), 1,
      sym_identifier,
    STATE(5), 5,
      sym_assignment,
      sym_transaction,
      sym__transaction_statement,
      sym_special_transaction,
      aux_sym_scoped_transaction_repeat1,
    ACTIONS(52), 7,
      anon_sym_add,
      anon_sym_rm,
      anon_sym_remove,
      anon_sym_sub,
      anon_sym_subtract,
      anon_sym_credit,
      anon_sym_debit,
  [110] = 8,
    ACTIONS(7), 1,
      anon_sym_entry,
    ACTIONS(9), 1,
      anon_sym_reference,
    ACTIONS(11), 1,
      anon_sym_for,
    ACTIONS(13), 1,
      anon_sym_in,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(58), 1,
      sym_comment,
    ACTIONS(60), 1,
      anon_sym_RBRACE,
    STATE(4), 7,
      sym__statement,
      sym_entry,
      sym_reference,
      sym_assignment,
      sym_transaction,
      sym_scoped_transaction,
      aux_sym_source_file_repeat1,
  [141] = 8,
    ACTIONS(7), 1,
      anon_sym_entry,
    ACTIONS(9), 1,
      anon_sym_reference,
    ACTIONS(11), 1,
      anon_sym_for,
    ACTIONS(13), 1,
      anon_sym_in,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(62), 1,
      sym_comment,
    ACTIONS(64), 1,
      anon_sym_RBRACE,
    STATE(9), 7,
      sym__statement,
      sym_entry,
      sym_reference,
      sym_assignment,
      sym_transaction,
      sym_scoped_transaction,
      aux_sym_source_file_repeat1,
  [172] = 8,
    ACTIONS(7), 1,
      anon_sym_entry,
    ACTIONS(9), 1,
      anon_sym_reference,
    ACTIONS(11), 1,
      anon_sym_for,
    ACTIONS(13), 1,
      anon_sym_in,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(66), 1,
      sym_comment,
    ACTIONS(68), 1,
      anon_sym_RBRACE,
    STATE(6), 7,
      sym__statement,
      sym_entry,
      sym_reference,
      sym_assignment,
      sym_transaction,
      sym_scoped_transaction,
      aux_sym_source_file_repeat1,
  [203] = 8,
    ACTIONS(7), 1,
      anon_sym_entry,
    ACTIONS(9), 1,
      anon_sym_reference,
    ACTIONS(11), 1,
      anon_sym_for,
    ACTIONS(13), 1,
      anon_sym_in,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(58), 1,
      sym_comment,
    ACTIONS(70), 1,
      anon_sym_RBRACE,
    STATE(4), 7,
      sym__statement,
      sym_entry,
      sym_reference,
      sym_assignment,
      sym_transaction,
      sym_scoped_transaction,
      aux_sym_source_file_repeat1,
  [234] = 8,
    ACTIONS(7), 1,
      anon_sym_entry,
    ACTIONS(9), 1,
      anon_sym_reference,
    ACTIONS(11), 1,
      anon_sym_for,
    ACTIONS(13), 1,
      anon_sym_in,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(58), 1,
      sym_comment,
    ACTIONS(72), 1,
      ts_builtin_sym_end,
    STATE(4), 7,
      sym__statement,
      sym_entry,
      sym_reference,
      sym_assignment,
      sym_transaction,
      sym_scoped_transaction,
      aux_sym_source_file_repeat1,
  [265] = 4,
    ACTIONS(74), 1,
      anon_sym_RBRACE,
    ACTIONS(78), 1,
      sym_identifier,
    STATE(13), 4,
      sym_assignment,
      sym__transaction_statement,
      sym_special_transaction,
      aux_sym_transaction_repeat1,
    ACTIONS(76), 7,
      anon_sym_add,
      anon_sym_rm,
      anon_sym_remove,
      anon_sym_sub,
      anon_sym_subtract,
      anon_sym_credit,
      anon_sym_debit,
  [287] = 4,
    ACTIONS(80), 1,
      anon_sym_RBRACE,
    ACTIONS(85), 1,
      sym_identifier,
    STATE(12), 4,
      sym_assignment,
      sym__transaction_statement,
      sym_special_transaction,
      aux_sym_transaction_repeat1,
    ACTIONS(82), 7,
      anon_sym_add,
      anon_sym_rm,
      anon_sym_remove,
      anon_sym_sub,
      anon_sym_subtract,
      anon_sym_credit,
      anon_sym_debit,
  [309] = 4,
    ACTIONS(78), 1,
      sym_identifier,
    ACTIONS(88), 1,
      anon_sym_RBRACE,
    STATE(12), 4,
      sym_assignment,
      sym__transaction_statement,
      sym_special_transaction,
      aux_sym_transaction_repeat1,
    ACTIONS(76), 7,
      anon_sym_add,
      anon_sym_rm,
      anon_sym_remove,
      anon_sym_sub,
      anon_sym_subtract,
      anon_sym_credit,
      anon_sym_debit,
  [331] = 4,
    ACTIONS(78), 1,
      sym_identifier,
    ACTIONS(90), 1,
      anon_sym_RBRACE,
    STATE(15), 4,
      sym_assignment,
      sym__transaction_statement,
      sym_special_transaction,
      aux_sym_transaction_repeat1,
    ACTIONS(76), 7,
      anon_sym_add,
      anon_sym_rm,
      anon_sym_remove,
      anon_sym_sub,
      anon_sym_subtract,
      anon_sym_credit,
      anon_sym_debit,
  [353] = 4,
    ACTIONS(78), 1,
      sym_identifier,
    ACTIONS(92), 1,
      anon_sym_RBRACE,
    STATE(12), 4,
      sym_assignment,
      sym__transaction_statement,
      sym_special_transaction,
      aux_sym_transaction_repeat1,
    ACTIONS(76), 7,
      anon_sym_add,
      anon_sym_rm,
      anon_sym_remove,
      anon_sym_sub,
      anon_sym_subtract,
      anon_sym_credit,
      anon_sym_debit,
  [375] = 2,
    ACTIONS(94), 1,
      anon_sym_RBRACE,
    ACTIONS(96), 9,
      anon_sym_for,
      anon_sym_add,
      anon_sym_rm,
      anon_sym_remove,
      anon_sym_sub,
      anon_sym_subtract,
      anon_sym_credit,
      anon_sym_debit,
      sym_identifier,
  [390] = 2,
    ACTIONS(98), 1,
      anon_sym_RBRACE,
    ACTIONS(100), 9,
      anon_sym_for,
      anon_sym_add,
      anon_sym_rm,
      anon_sym_remove,
      anon_sym_sub,
      anon_sym_subtract,
      anon_sym_credit,
      anon_sym_debit,
      sym_identifier,
  [405] = 2,
    ACTIONS(102), 1,
      anon_sym_RBRACE,
    ACTIONS(104), 9,
      anon_sym_for,
      anon_sym_add,
      anon_sym_rm,
      anon_sym_remove,
      anon_sym_sub,
      anon_sym_subtract,
      anon_sym_credit,
      anon_sym_debit,
      sym_identifier,
  [420] = 2,
    ACTIONS(106), 1,
      anon_sym_RBRACE,
    ACTIONS(108), 9,
      anon_sym_for,
      anon_sym_add,
      anon_sym_rm,
      anon_sym_remove,
      anon_sym_sub,
      anon_sym_subtract,
      anon_sym_credit,
      anon_sym_debit,
      sym_identifier,
  [435] = 2,
    ACTIONS(110), 1,
      anon_sym_RBRACE,
    ACTIONS(112), 9,
      anon_sym_for,
      anon_sym_add,
      anon_sym_rm,
      anon_sym_remove,
      anon_sym_sub,
      anon_sym_subtract,
      anon_sym_credit,
      anon_sym_debit,
      sym_identifier,
  [450] = 2,
    ACTIONS(114), 1,
      anon_sym_RBRACE,
    ACTIONS(116), 9,
      anon_sym_for,
      anon_sym_add,
      anon_sym_rm,
      anon_sym_remove,
      anon_sym_sub,
      anon_sym_subtract,
      anon_sym_credit,
      anon_sym_debit,
      sym_identifier,
  [465] = 2,
    ACTIONS(98), 1,
      anon_sym_RBRACE,
    ACTIONS(100), 8,
      anon_sym_add,
      anon_sym_rm,
      anon_sym_remove,
      anon_sym_sub,
      anon_sym_subtract,
      anon_sym_credit,
      anon_sym_debit,
      sym_identifier,
  [479] = 2,
    ACTIONS(102), 1,
      anon_sym_RBRACE,
    ACTIONS(104), 8,
      anon_sym_add,
      anon_sym_rm,
      anon_sym_remove,
      anon_sym_sub,
      anon_sym_subtract,
      anon_sym_credit,
      anon_sym_debit,
      sym_identifier,
  [493] = 2,
    ACTIONS(110), 1,
      anon_sym_RBRACE,
    ACTIONS(112), 8,
      anon_sym_add,
      anon_sym_rm,
      anon_sym_remove,
      anon_sym_sub,
      anon_sym_subtract,
      anon_sym_credit,
      anon_sym_debit,
      sym_identifier,
  [507] = 2,
    ACTIONS(106), 1,
      anon_sym_RBRACE,
    ACTIONS(108), 8,
      anon_sym_add,
      anon_sym_rm,
      anon_sym_remove,
      anon_sym_sub,
      anon_sym_subtract,
      anon_sym_credit,
      anon_sym_debit,
      sym_identifier,
  [521] = 2,
    ACTIONS(114), 3,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_RBRACE,
    ACTIONS(116), 5,
      anon_sym_entry,
      anon_sym_reference,
      anon_sym_for,
      anon_sym_in,
      sym_identifier,
  [534] = 2,
    ACTIONS(118), 3,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_RBRACE,
    ACTIONS(120), 5,
      anon_sym_entry,
      anon_sym_reference,
      anon_sym_for,
      anon_sym_in,
      sym_identifier,
  [547] = 2,
    ACTIONS(122), 3,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_RBRACE,
    ACTIONS(124), 5,
      anon_sym_entry,
      anon_sym_reference,
      anon_sym_for,
      anon_sym_in,
      sym_identifier,
  [560] = 2,
    ACTIONS(110), 3,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_RBRACE,
    ACTIONS(112), 5,
      anon_sym_entry,
      anon_sym_reference,
      anon_sym_for,
      anon_sym_in,
      sym_identifier,
  [573] = 2,
    ACTIONS(126), 3,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_RBRACE,
    ACTIONS(128), 5,
      anon_sym_entry,
      anon_sym_reference,
      anon_sym_for,
      anon_sym_in,
      sym_identifier,
  [586] = 2,
    ACTIONS(130), 3,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_RBRACE,
    ACTIONS(132), 5,
      anon_sym_entry,
      anon_sym_reference,
      anon_sym_for,
      anon_sym_in,
      sym_identifier,
  [599] = 2,
    ACTIONS(94), 3,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_RBRACE,
    ACTIONS(96), 5,
      anon_sym_entry,
      anon_sym_reference,
      anon_sym_for,
      anon_sym_in,
      sym_identifier,
  [612] = 2,
    ACTIONS(102), 3,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_RBRACE,
    ACTIONS(104), 5,
      anon_sym_entry,
      anon_sym_reference,
      anon_sym_for,
      anon_sym_in,
      sym_identifier,
  [625] = 2,
    ACTIONS(106), 3,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_RBRACE,
    ACTIONS(108), 5,
      anon_sym_entry,
      anon_sym_reference,
      anon_sym_for,
      anon_sym_in,
      sym_identifier,
  [638] = 2,
    ACTIONS(134), 3,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_RBRACE,
    ACTIONS(136), 5,
      anon_sym_entry,
      anon_sym_reference,
      anon_sym_for,
      anon_sym_in,
      sym_identifier,
  [651] = 2,
    ACTIONS(138), 3,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_RBRACE,
    ACTIONS(140), 5,
      anon_sym_entry,
      anon_sym_reference,
      anon_sym_for,
      anon_sym_in,
      sym_identifier,
  [664] = 4,
    ACTIONS(142), 1,
      anon_sym_LBRACE,
    ACTIONS(144), 1,
      sym_number,
    ACTIONS(146), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(34), 3,
      sym__value,
      sym_string,
      sym_boolean,
  [680] = 4,
    ACTIONS(148), 1,
      anon_sym_LBRACE,
    ACTIONS(150), 1,
      sym_number,
    ACTIONS(152), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(19), 3,
      sym__value,
      sym_string,
      sym_boolean,
  [696] = 4,
    ACTIONS(154), 1,
      anon_sym_LBRACE,
    ACTIONS(156), 1,
      sym_number,
    ACTIONS(158), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(25), 3,
      sym__value,
      sym_string,
      sym_boolean,
  [712] = 3,
    ACTIONS(160), 1,
      anon_sym_RPAREN,
    ACTIONS(162), 1,
      anon_sym_DASH_GT,
    STATE(40), 1,
      aux_sym_entity_reference_repeat1,
  [722] = 3,
    ACTIONS(165), 1,
      anon_sym_RPAREN,
    ACTIONS(167), 1,
      anon_sym_DASH_GT,
    STATE(42), 1,
      aux_sym_entity_reference_repeat1,
  [732] = 3,
    ACTIONS(167), 1,
      anon_sym_DASH_GT,
    ACTIONS(169), 1,
      anon_sym_RPAREN,
    STATE(40), 1,
      aux_sym_entity_reference_repeat1,
  [742] = 2,
    ACTIONS(171), 1,
      sym_identifier,
    STATE(58), 1,
      sym_entity_reference,
  [749] = 1,
    ACTIONS(160), 2,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
  [754] = 2,
    ACTIONS(171), 1,
      sym_identifier,
    STATE(52), 1,
      sym_entity_reference,
  [761] = 2,
    ACTIONS(171), 1,
      sym_identifier,
    STATE(50), 1,
      sym_entity_reference,
  [768] = 2,
    ACTIONS(171), 1,
      sym_identifier,
    STATE(72), 1,
      sym_entity_reference,
  [775] = 2,
    ACTIONS(171), 1,
      sym_identifier,
    STATE(76), 1,
      sym_entity_reference,
  [782] = 1,
    ACTIONS(173), 1,
      anon_sym_EQ,
  [786] = 1,
    ACTIONS(175), 1,
      anon_sym_RPAREN,
  [790] = 1,
    ACTIONS(177), 1,
      anon_sym_LPAREN,
  [794] = 1,
    ACTIONS(179), 1,
      anon_sym_RPAREN,
  [798] = 1,
    ACTIONS(181), 1,
      aux_sym_string_token1,
  [802] = 1,
    ACTIONS(183), 1,
      anon_sym_LBRACE,
  [806] = 1,
    ACTIONS(185), 1,
      anon_sym_LBRACE,
  [810] = 1,
    ACTIONS(187), 1,
      sym_number,
  [814] = 1,
    ACTIONS(189), 1,
      anon_sym_LPAREN,
  [818] = 1,
    ACTIONS(191), 1,
      anon_sym_RPAREN,
  [822] = 1,
    ACTIONS(193), 1,
      anon_sym_LPAREN,
  [826] = 1,
    ACTIONS(195), 1,
      sym_identifier,
  [830] = 1,
    ACTIONS(197), 1,
      anon_sym_RBRACE,
  [834] = 1,
    ACTIONS(199), 1,
      sym_number,
  [838] = 1,
    ACTIONS(201), 1,
      anon_sym_EQ,
  [842] = 1,
    ACTIONS(203), 1,
      anon_sym_LBRACE,
  [846] = 1,
    ACTIONS(205), 1,
      anon_sym_in,
  [850] = 1,
    ACTIONS(207), 1,
      anon_sym_RBRACE,
  [854] = 1,
    ACTIONS(209), 1,
      anon_sym_EQ,
  [858] = 1,
    ACTIONS(211), 1,
      aux_sym_string_token1,
  [862] = 1,
    ACTIONS(213), 1,
      anon_sym_LBRACE,
  [866] = 1,
    ACTIONS(215), 1,
      anon_sym_LBRACE,
  [870] = 1,
    ACTIONS(217), 1,
      aux_sym_string_token1,
  [874] = 1,
    ACTIONS(219), 1,
      anon_sym_RPAREN,
  [878] = 1,
    ACTIONS(221), 1,
      anon_sym_RBRACE,
  [882] = 1,
    ACTIONS(223), 1,
      anon_sym_LPAREN,
  [886] = 1,
    ACTIONS(225), 1,
      anon_sym_in,
  [890] = 1,
    ACTIONS(227), 1,
      anon_sym_RPAREN,
  [894] = 1,
    ACTIONS(229), 1,
      ts_builtin_sym_end,
  [898] = 1,
    ACTIONS(231), 1,
      anon_sym_LPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 26,
  [SMALL_STATE(4)] = 52,
  [SMALL_STATE(5)] = 84,
  [SMALL_STATE(6)] = 110,
  [SMALL_STATE(7)] = 141,
  [SMALL_STATE(8)] = 172,
  [SMALL_STATE(9)] = 203,
  [SMALL_STATE(10)] = 234,
  [SMALL_STATE(11)] = 265,
  [SMALL_STATE(12)] = 287,
  [SMALL_STATE(13)] = 309,
  [SMALL_STATE(14)] = 331,
  [SMALL_STATE(15)] = 353,
  [SMALL_STATE(16)] = 375,
  [SMALL_STATE(17)] = 390,
  [SMALL_STATE(18)] = 405,
  [SMALL_STATE(19)] = 420,
  [SMALL_STATE(20)] = 435,
  [SMALL_STATE(21)] = 450,
  [SMALL_STATE(22)] = 465,
  [SMALL_STATE(23)] = 479,
  [SMALL_STATE(24)] = 493,
  [SMALL_STATE(25)] = 507,
  [SMALL_STATE(26)] = 521,
  [SMALL_STATE(27)] = 534,
  [SMALL_STATE(28)] = 547,
  [SMALL_STATE(29)] = 560,
  [SMALL_STATE(30)] = 573,
  [SMALL_STATE(31)] = 586,
  [SMALL_STATE(32)] = 599,
  [SMALL_STATE(33)] = 612,
  [SMALL_STATE(34)] = 625,
  [SMALL_STATE(35)] = 638,
  [SMALL_STATE(36)] = 651,
  [SMALL_STATE(37)] = 664,
  [SMALL_STATE(38)] = 680,
  [SMALL_STATE(39)] = 696,
  [SMALL_STATE(40)] = 712,
  [SMALL_STATE(41)] = 722,
  [SMALL_STATE(42)] = 732,
  [SMALL_STATE(43)] = 742,
  [SMALL_STATE(44)] = 749,
  [SMALL_STATE(45)] = 754,
  [SMALL_STATE(46)] = 761,
  [SMALL_STATE(47)] = 768,
  [SMALL_STATE(48)] = 775,
  [SMALL_STATE(49)] = 782,
  [SMALL_STATE(50)] = 786,
  [SMALL_STATE(51)] = 790,
  [SMALL_STATE(52)] = 794,
  [SMALL_STATE(53)] = 798,
  [SMALL_STATE(54)] = 802,
  [SMALL_STATE(55)] = 806,
  [SMALL_STATE(56)] = 810,
  [SMALL_STATE(57)] = 814,
  [SMALL_STATE(58)] = 818,
  [SMALL_STATE(59)] = 822,
  [SMALL_STATE(60)] = 826,
  [SMALL_STATE(61)] = 830,
  [SMALL_STATE(62)] = 834,
  [SMALL_STATE(63)] = 838,
  [SMALL_STATE(64)] = 842,
  [SMALL_STATE(65)] = 846,
  [SMALL_STATE(66)] = 850,
  [SMALL_STATE(67)] = 854,
  [SMALL_STATE(68)] = 858,
  [SMALL_STATE(69)] = 862,
  [SMALL_STATE(70)] = 866,
  [SMALL_STATE(71)] = 870,
  [SMALL_STATE(72)] = 874,
  [SMALL_STATE(73)] = 878,
  [SMALL_STATE(74)] = 882,
  [SMALL_STATE(75)] = 886,
  [SMALL_STATE(76)] = 890,
  [SMALL_STATE(77)] = 894,
  [SMALL_STATE(78)] = 898,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_scoped_transaction_repeat1, 2, 0, 0),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_scoped_transaction_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_scoped_transaction_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_scoped_transaction_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [78] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_transaction_repeat1, 2, 0, 0),
  [82] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_transaction_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [85] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_transaction_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_transaction, 11, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_transaction, 11, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_special_transaction, 2, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_special_transaction, 2, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 3, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_transaction, 10, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_transaction, 10, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scoped_transaction, 7, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scoped_transaction, 7, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entry, 3, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_entry, 3, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_reference, 3, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_reference, 3, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scoped_transaction, 6, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scoped_transaction, 6, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entry, 4, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_entry, 4, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_reference, 4, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_reference, 4, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_entity_reference_repeat1, 2, 0, 0),
  [162] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_entity_reference_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entity_reference, 1, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entity_reference, 2, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [229] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_ec(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "ec",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
